In [ ]:
import tensorflow.keras
import numpy as np
import pandas as pd
import tensorflow as tf


**tensorflow operations**

In [ ]:
#在tf中生成變數，初始值為隨機
v = tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 1.1514196 ],
       [-0.13220641],
       [-0.33578503]], dtype=float32)>

In [ ]:
#賦予1在矩陣裡面
v.assign(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
#在陣列裡各加上1
v.assign_add(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[2.],
       [2.],
       [2.]], dtype=float32)>

In [ ]:
#在0,0位置的值改成3
v[0,0].assign(3)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [2.],
       [2.]], dtype=float32)>

In [ ]:
a = tf.random.normal((2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
e *= d
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[0.22565795 0.9469915 ]
 [0.8067066  1.8031243 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.05092151 0.8967929 ]
 [0.65077555 3.2512572 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.47503468 0.9731349 ]
 [0.89816844 1.3428047 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.5259562 1.8699278]
 [1.548944  4.594062 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.33017942  6.1357594 ]
 [ 1.8812047  30.255894  ]], shape=(2, 2), dtype=float32)
